"use client";

import { useState, useEffect, useRef, useMemo, use } from "react";
import Link from "next/link";
import COURSE_REGISTRY from "@/data/registry";
import type { LessonWithUnit } from "@/types";
import { getCourseProgress, setLessonDone } from "@/lib/progress";
import DonationModal from "@/components/ui/DonationModal";
import FlipCard from "@/components/ui/FlipCard";
import PracticeQuestion from "@/components/ui/PracticeQuestion";
import {
  StatsRow, EcosystemDiagram, Triangle, PhaseTimeline,
  DimensionWheel, CharacteristicsGrid, BTPStack, BeforeAfter,
  RISEvsGROW, PathwaysViz, ComponentPillars, EnhancementCards,
  BenefitsGrid,
} from "@/components/visuals/index";
import ITPillars from "@/components/visuals/ITPillars";
import ToolsTable from "@/components/visuals/ToolsTable";
import CleanStateVisual from "@/components/visuals/CleanStateVisual";
import { u1l1Questions } from "@/data/courses/rise-with-sap/questions/u1l1";
import { u1l2Questions } from "@/data/courses/rise-with-sap/questions/u1l2";
import { u1l3Questions } from "@/data/courses/rise-with-sap/questions/u1l3";
import type { TopicVisual } from "@/types";

const LESSON_META: Record<string, { intro: string; topics: string[]; topicTitles: string[] }> = {
  "u1l1": { intro: "Set the stage — what SAP Business Suite is, why it was created, and how companies get there.", topics: ["u1l1-t1","u1l1-t2","u1l1-t3","u1l1-t4","u1l1-t5"], topicTitles: ["Why Businesses Need to Transform","What is the SAP Business Suite","The 4 IT Challenges SAP Addresses","RISE vs GROW — Two Journeys","Pathways to the SAP Business Suite"] },
  "u1l2": { intro: "The RISE with SAP Methodology in depth — structure, three core components, six phases, and benefits. Most heavily tested area.", topics: ["u1l2-t1","u1l2-t2","u1l2-t3","u1l2-t4","u1l2-t5","u1l2-t6"], topicTitles: ["What is the RISE with SAP Methodology","People, Processes, Tools — The 3 Pillars","The 3 Core Components","The 6 Phases — Discover to Run","5 Methodology Enhancements","Key Benefits + Tools & Services"] },
  "u1l3": { intro: "Clean Core is the foundation everything else builds on. Understand it deeply here.", topics: ["u1l3-t1","u1l3-t2","u1l3-t3","u1l3-t4","u1l3-t5","u1l3-t6"], topicTitles: ["Why Clean Core Was Needed","The 5 Core Dimensions","What 'Clean' Actually Means","5 Characteristics of a Clean System","BTP's Role — Extensions Outside the Core","Old ERP vs Clean Core"] },
};

function getVisuals(): Record<string, TopicVisual> {
  return {
    "u1l1-t1": { visual: () => <StatsRow stats={[{icon:"🏭",to:850,suffix:"+",label:"Custom ABAP programs avg ECC company",color:"#DC2626"},{icon:"📅",to:15,suffix:" yrs",label:"Akshar on SAP ECC without major upgrade",color:"#D97706"},{icon:"🌍",to:25,suffix:"+",label:"Industries SAP has expertise in",color:"#0070F2"}]} />, keyPoints:["The question is never WHETHER to transform — it's HOW","Heavy custom ECC systems can't absorb SAP's quarterly cloud updates","SAP's approach: outcome-focused, not just 'install software'"], jargon:[{term:"On-Premise ERP",simple:"SAP software on the company's own servers.",inSystem:"The 'old way' like SAP ECC — starting point companies move AWAY from via RISE.",inExam:"Usually appears as the starting point that companies are moving away from.",color:"#DC2626"},{term:"Digital Transformation",simple:"Overhauling how a business operates using modern technology.",inSystem:"On-premise ERP → cloud ERP with modern processes.",inExam:"SAP frames it as 'not whether to transform, but how.'",color:"#0070F2"}], akshar:"Akshar Industries, Ahmedabad. Running SAP ECC since 2009. 850+ custom programs over 15 years. Every upgrade attempt failed — too risky to retest all custom code. CIO Nirav Shah told the board: 'We are falling behind competitors using AI. We need to transform — and we need a structured way to do it.'", exam:"SAP explicitly states expertise across 25+ industries. The key phrase is 'not whether to transform, but how.' Questions test this framing — the answer is always about HOW, not IF.", mistake:"Thinking transformation is purely a technology project. SAP builds it around People, Processes, AND Tools.", summary:["Digital economy makes transformation unavoidable — the only question is HOW.","Companies on legacy ECC face upgrade backlogs, complexity, and innovation gaps.","SAP brings 25+ industry expertise to guide outcome-focused transformations."], questions: u1l1Questions.t1 },
    "u1l1-t2": { visual: () => <EcosystemDiagram />, keyPoints:["The Suite is SAP's complete cloud portfolio — NOT just S/4HANA","Goal: enhance connectivity and optimise functions across enterprises","Includes: Cloud ERP + BTP + Business Data Cloud + Business AI + LoB Solutions"], jargon:[{term:"SAP Business Suite",simple:"SAP's full collection of cloud products working together as one ecosystem.",inSystem:"Includes Cloud ERP, BTP, Business Data Cloud, Business AI, and LoB solutions.",inExam:"Its main goal is to 'enhance connectivity and optimise functions.'",color:"#0070F2"},{term:"SAP BTP",simple:"SAP's platform for building custom apps and integrations.",inSystem:"The extension layer — where customisations go so the core stays clean.",inExam:"BTP appears repeatedly. It is the platform for extensions AND integrations.",color:"#7C3AED"}], akshar:"Before RISE, Akshar thought of SAP as just their ECC system. Post-RISE, Nirav Shah tells the board: We are not getting an upgrade — we are getting the entire SAP Business Suite. S/4HANA for operations, BTP for custom apps, Business Data Cloud for analytics, Business AI built into our processes.", exam:"Main goal of SAP Business Suite = 'enhance connectivity and optimise functions across enterprises.' Common wrong answer: 'simplify IT infrastructure'.", mistake:"Students think SAP Business Suite = SAP S/4HANA. It is the entire portfolio. S/4HANA is just the ERP component at the centre.", summary:["Business Suite = full cloud portfolio: ERP + BTP + Business Data Cloud + Business AI + LoB.","Main goal: enhance connectivity and optimise functions across enterprises.","It is an integrated ecosystem — not a single product."], questions: u1l1Questions.t2 },
    "u1l1-t3": { visual: () => <ITPillars />, keyPoints:["SAP identifies exactly 4 IT challenges — no more, no less","The RISE Methodology directly answers all 4","Distractors: cost reduction, market expansion, workforce development — never in the official 4"], jargon:[{term:"Implementation Framework",simple:"A structured playbook: what to do, in what order, at every stage.",inSystem:"SAP provides this through SAP Activate + RISE Methodology.",inExam:"Always appears as proven implementation framework — the word proven matters.",color:"#0070F2"},{term:"Best Practices",simple:"SAP's recommended, pre-built way of running business processes.",inSystem:"Built into S/4HANA out of the box. Using them = Clean Core.",inExam:"Best practices = what companies adopt by following standard SAP processes.",color:"#7C3AED"}], akshar:"When Akshar started their migration research, they had none of the 4: no structured framework (two failed attempts), no best practices, no expert support, and no proper tools (managing in spreadsheets).", exam:"These 4 challenges appear in multi-select questions. Distractors: cost reduction, rapid market expansion, developing a global workforce.", mistake:"Adding cost reduction as one of the four. SAP does not list it. The 4 are: proven framework, best practices, expert navigational support, right tools.", summary:["SAP identifies exactly 4 IT challenges: proven framework, best practices, navigational support, right tools.","The RISE Methodology directly answers all 4.","Watch for distractors like cost reduction and market expansion."], questions: u1l1Questions.t3 },
    "u1l1-t4": { visual: () => <RISEvsGROW />, keyPoints:["RISE = existing on-premise SAP customers migrating to cloud","GROW = new SAP customers, straight to Public Cloud","SAP Cloud ERP Private Package is RISE's key offering for large enterprises"], jargon:[{term:"RISE with SAP",simple:"SAP's structured transformation journey for existing on-premise SAP customers moving to cloud.",inSystem:"Includes methodology, tools, services, and expert guidance.",inExam:"RISE = existing customers. Comes with SAP Cloud ERP Private Package for large enterprises.",color:"#0070F2"},{term:"GROW with SAP",simple:"SAP's path for new customers adopting SAP for the first time, going straight to Public Cloud.",inSystem:"Faster, simpler, based on SAP Best Practices from day one.",inExam:"GROW = new customers. Public Cloud. Not the focus of this course.",color:"#059669"}], akshar:"Akshar Industries = RISE candidate. Running ECC since 2009, 850+ custom programs — cannot just start fresh. Contrast: new pharma startup in Hyderabad with no SAP history goes GROW, straight to S/4HANA Public Cloud, live in months.", exam:"RISE = existing on-premise SAP customers. GROW = new SAP customers. SAP Cloud ERP Private Package is the key RISE offering for large enterprises.", mistake:"Confusing RISE and GROW as the same journey with different names. They serve fundamentally different customer profiles.", summary:["RISE = structured journey for existing on-premise SAP customers migrating to cloud.","GROW = fast path for net-new SAP customers, straight to Public Cloud.","SAP Cloud ERP Private Package is RISE key offering — includes S/4HANA Private Edition + tooling."], questions: u1l1Questions.t4 },
    "u1l1-t5": { visual: () => <PathwaysViz />, keyPoints:["Three pathways: Full Public Cloud, Hybrid, Two-Tier","Hybrid in SAP = private + public cloud — NOT cloud + on-premise","All pathways supported by BTP + Business Data Cloud + Business AI"], jargon:[{term:"Hybrid Model",simple:"Mixing SAP Cloud ERP Private for complex areas with SAP Cloud ERP Public for simpler areas in one organisation.",inSystem:"HQ on Private Edition, new factories on Public Edition.",inExam:"Hybrid = private + public cloud. NOT half-cloud half-on-premise.",color:"#7C3AED"},{term:"Two-Tier Implementation",simple:"Running both Private and Public cloud ERP simultaneously across different parts of the same company.",inSystem:"Parent company on Private + each subsidiary on Public. All integrated via BTP.",inExam:"Specific term for concurrent deployment of both editions.",color:"#059669"}], akshar:"Akshar plan: Ahmedabad HQ on S/4HANA Cloud Private Edition. New Pune plant on S/4HANA Cloud Public Edition. Both connected via BTP. Data flows via Business Data Cloud. This is the two-tier model in practice.", exam:"The exam tests whether you know hybrid means private + public cloud — not cloud + on-premise.", mistake:"Thinking hybrid means keeping some systems on-premise. In SAP context, hybrid = private + public cloud editions — it is all cloud.", summary:["Three pathways: full public, hybrid private+public, or two-tier both concurrent.","Two-tier = Private at HQ + Public at subsidiaries, integrated via BTP.","Hybrid in SAP = cloud-to-cloud mix — NOT cloud + on-premise."], questions: u1l1Questions.t5 },
    "u1l2-t1": { visual: () => <BeforeAfter before={["RISE with SAP — The Offering","Products and Licences you buy","S/4HANA, BTP, Signavio..."]} after={["RISE Methodology — The Framework","HOW you implement those products","Phases, tasks, quality gates, guidance"]} />, keyPoints:["The Methodology is the how — the offering is the what","Built on SAP Activate — the existing proven implementation framework","Works across all SAP Business Suite configurations"], jargon:[{term:"SAP Activate Methodology",simple:"SAP's established implementation methodology — the underlying framework RISE Methodology builds upon.",inSystem:"Provides the phase structure Discover to Run, templates, and tasks that RISE enhances.",inExam:"RISE methodology augments SAP Activate — it does not replace it.",color:"#0070F2"},{term:"Clean Core Strategy",simple:"The guiding principle that keeps the ERP system standard and moves customisations outside the core.",inSystem:"The Methodology is built on a clean core strategy.",inExam:"Clean Core is both a strategy and a measurable outcome of following RISE Methodology.",color:"#059669"}], akshar:"When TechNova starts the project, PM Priya Desai does not create a plan from scratch. She opens SAP Cloud ALM, loads the RISE Methodology, and gets pre-built tasks for every phase. Arjun from SAP walks through exactly what Akshar needs in Discover. The Methodology is their GPS.", exam:"Key distinction: RISE with SAP the offering vs RISE Methodology the framework. Methodology = structured guidance.", mistake:"Treating Methodology and the RISE product package as the same thing. Package = products + licences. Methodology = phases + guidance + tools.", summary:["RISE Methodology = structured framework for cloud transformation, built on SAP Activate.","Provides guidance across defined phases with SAP experts and integrated toolchain.","Built on Clean Core strategy — every phase keeps the ERP clean."], questions: u1l2Questions.t1 },
    "u1l2-t2": { visual: () => <Triangle />, keyPoints:["The transformation journey hinges on people, processes, and tools — SAP exact phrase","NOT technology — the word is tools. A subtle but testable difference","All three must work together — missing one causes the transformation to fail"], jargon:[{term:"People-Process-Tools",simple:"SAP's model: successful transformation requires all three elements working in sync.",inSystem:"Every aspect of the RISE Methodology maps to one of these three pillars.",inExam:"SAP uses tools — NOT technology. That single word difference can cost you a mark.",color:"#0070F2"}], akshar:"Akshar transformation: People = Nirav Shah CIO, Priya Desai PM, Arjun Kapoor SAP. Processes = procure-to-pay, order-to-cash. Tools = Signavio, Cloud ALM, BTP.", exam:"SAP uses the word Tools — NOT Technology. If an exam option says People, Processes, Technology it is a trap.", mistake:"Writing Technology instead of Tools. SAP is specific about this language.", summary:["Hinges on people, processes, and tools — SAP exact phrase. Memorise it.","People = teams and experts. Processes = business flows. Tools = digital products.","All three must work together."], questions: u1l2Questions.t2 },
    "u1l2-t3": { visual: () => <ComponentPillars />, keyPoints:["Three components: Standardised Framework, Integrated Toolchain, Expert Guidance","Each maps to the People/Process/Tools triangle","Best Practices is NOT a 4th component — it is embedded inside the Framework"], jargon:[{term:"Standardised Framework",simple:"The enhanced SAP Activate roadmap — a step-by-step guide with Clean Core activities built in.",inSystem:"Adds tasks, quality gates, and deliverables to SAP Activate phases for Clean Core compliance.",inExam:"Official benefit phrase: for faster adoption tailored to business needs.",color:"#0070F2"},{term:"Integrated Toolchain",simple:"The recommended set of SAP tools working together for end-to-end transformation.",inSystem:"Signavio + LeanIX + Cloud ALM + BTP. Pre-integrated.",inExam:"Official benefit phrase: streamlined collaboration and project execution.",color:"#7C3AED"},{term:"Expert Guidance",simple:"SAP-provided human support — Onboarding Advisors, Enterprise Architects, certified partners.",inSystem:"Available through 4 onboarding calls and ongoing engagement.",inExam:"Official benefit phrase: end-to-end engagement.",color:"#059669"}], akshar:"Framework: Priya uses Clean Core Runbook in Cloud ALM — 150+ tasks pre-loaded. Toolchain: Signavio maps processes then LeanIX maps IT landscape then Cloud ALM tracks tasks. Expert Guidance: Arjun hosts 4 onboarding calls.", exam:"Multi-select: which 3 are core components? Answer: Standardised Framework + Integrated Toolchain + Expert Guidance.", mistake:"Listing Best Practices as a fourth component. It is embedded INSIDE the Standardised Framework.", summary:["Three components: Standardised Framework what to do, Toolchain manage it, Expert Guidance human support.","Framework maps to Processes, Toolchain maps to Tools, Expert Guidance maps to People.","Know all three — multi-select will test with convincing distractors."], questions: u1l2Questions.t3 },
    "u1l2-t4": { visual: () => <PhaseTimeline />, keyPoints:["Six phases: Discover, Prepare, Explore, Realize, Deploy, Run","DDA = Discover. 4 Onboarding Calls = Prepare. Quality Gates = Explore through Run","Quality Gates do NOT start in Discover or Prepare"], jargon:[{term:"Digital Discovery Assessment DDA",simple:"Structured toolkit used in the Discover phase to capture the customer current landscape.",inSystem:"Guides onboarding team in collecting the right data before the project starts.",inExam:"DDA belongs specifically to the Discover phase.",color:"#0070F2"},{term:"Clean Core Quality Gates",simple:"Checkpoints at the end of each phase Explore through Run where the team verifies Clean Core compliance.",inSystem:"Questionnaires managed through SAP Cloud ALM.",inExam:"Quality Gates happen in Explore, Realize, Deploy, and Run — NOT in Discover or Prepare.",color:"#7C3AED"}], akshar:"Akshar journey: Discover = Arjun runs DDA with Nirav. Prepare = 4 onboarding calls. Explore = Priya maps procure-to-pay in Signavio. Realize = BTP vendor rating app built. Deploy = go-live. Run = monitoring via Cloud ALM.", exam:"Quality Gates apply to Explore through Run. Discover = DDA. Prepare = onboarding sessions.", mistake:"Thinking Quality Gates start from the Discover phase. They start from Explore.", summary:["Six phases: Discover, Prepare, Explore, Realize, Deploy, Run.","Discover = DDA. Prepare = 4 calls + Success Plan. Explore through Run = Quality Gates.","Deploy = go-live. Run = ongoing operations + continuous improvement."], questions: u1l2Questions.t4 },
    "u1l2-t5": { visual: () => <EnhancementCards />, keyPoints:["5 specific enhancements to the RISE Methodology","TPS Enhancement 3 is ONLY for SAP Cloud ERP Private Package customers","Clean Core Success Plan = 150+ tasks in Cloud ALM"], jargon:[{term:"Transformation Preparation Service TPS",simple:"A specialised SAP-led service during the Prepare phase for SAP Cloud ERP Private Package customers.",inSystem:"Intensive 3-day workshop bridging the gap between pre-sales vision and post-sales execution.",inExam:"TPS is specifically for SAP Cloud ERP Private Package customers — not all RISE customers.",color:"#7C3AED"},{term:"Clean Core Success Plan",simple:"A plan in SAP Cloud ALM containing 150+ recommended tasks for maintaining Clean Core.",inSystem:"Lives in SAP Cloud ALM as a runbook.",inExam:"Set up during Prepare phase. 150+ tasks auto-loaded.",color:"#059669"}], akshar:"TPS triggered because Akshar is on Private Package — Arjun leads a 3-day workshop. Priya sets up the Clean Core Success Plan in Cloud ALM — 150+ tasks auto-loaded instantly.", exam:"TPS is specifically for SAP Cloud ERP Private Package customers — frequent exam trap.", mistake:"Saying TPS is available to all SAP customers. It is specifically for SAP Cloud ERP Private Package customers.", summary:["5 enhancements: DDA, broader roadmaps, TPS for Private customers, improved onboarding plus Success Plan, enhanced toolchain.","TPS exclusively for SAP Cloud ERP Private Package customers.","Success Plan = 150+ tasks in Cloud ALM, set up during Prepare."], questions: u1l2Questions.t5 },
    "u1l2-t6": { visual: () => <div className="flex flex-col gap-3"><BenefitsGrid /><ToolsTable /></div>, keyPoints:["Four benefits: Predictability, Transparency, Access to info, SAP support at any time","Signavio = Process Analysis. LeanIX = Enterprise Architecture. Do not mix these.","TPS = transformation service. Embedded launch activities = onboarding service."], jargon:[{term:"SAP Signavio",simple:"SAP suite of process analysis and management tools.",inSystem:"Used to map current processes vs SAP best practice.",inExam:"Signavio = process analysis. Always paired with LeanIX.",color:"#0070F2"},{term:"SAP LeanIX",simple:"SAP enterprise architecture tool.",inSystem:"Maps all current systems and plans the target architecture.",inExam:"LeanIX = enterprise architecture. Signavio = processes. Do not mix these.",color:"#7C3AED"}], akshar:"Nirav board asks: How do we know the project is on track? Nirav: Predictability — quality gates. Transparency — Cloud ALM dashboard visible to all. Info is always available. And Arjun from SAP is a call away.", exam:"All 4 benefits tested — often 3 correct from 5. Wrong options: enhanced employee engagement and improved marketing analytics.", mistake:"Mixing up Signavio process analysis with LeanIX enterprise architecture.", summary:["Four benefits: Predictability, Transparency, Access to info, Support at any time.","Signavio 6 tools for process analysis; LeanIX 3 tools for enterprise architecture.","TPS = transformation service. Embedded launch activities = onboarding service."], questions: u1l2Questions.t6 },
    "u1l3-t1": { visual: () => <BeforeAfter before={["850+ custom programs","Upgrade attempts: 18 months","3 failed upgrade projects","70% IT budget on maintenance","Cannot adopt new SAP AI features"]} after={["Zero custom code inside S/4HANA core","Quarterly updates applied in hours","Extensions live on BTP — unaffected","30% IT budget on maintenance","Joule AI live from Day 1 of go-live"]} />, keyPoints:["Clean Core = keep the ERP core standard, build all custom needs on BTP","Does NOT mean zero customisation — it means customisation outside the core","Cloud ERP updates are quarterly — dirty core = cannot absorb them"], jargon:[{term:"Clean Core",simple:"Keep S/4HANA as close to SAP standard as possible. All custom development goes outside on BTP.",inSystem:"Enables quarterly upgrades in hours instead of 18-month projects.",inExam:"Keeping the core close to standard version, avoiding heavy customisations — SAP exact definition.",color:"#0070F2"},{term:"SAP ECC",simple:"SAP previous-generation on-premise ERP — what most RISE customers are migrating FROM.",inSystem:"Designed for heavy customisation, which is now the problem.",inExam:"ECC appears as the starting point companies are moving away from via RISE.",color:"#DC2626"}], akshar:"Akshar 2015 upgrade attempt: estimated 18 months just to retest 850 custom programs. Shelved. 2019: same story. Post-Clean Core: new S/4HANA has zero custom code inside core. Quarterly updates applied in one afternoon.", exam:"SAP exact definition: keeping the core system close to the standard version, avoiding heavy customisations that complicate updates and maintenance.", mistake:"Thinking Clean Core means zero customisation. It means customisations are built OUTSIDE the core on BTP.", summary:["Clean Core: keep S/4HANA standard. Custom needs go to SAP BTP, not inside the core.","Enables quarterly updates in hours instead of 18-month projects.","Clean Core does not mean no customisation. It means customisation outside the core."], questions: u1l3Questions.t1 },
    "u1l3-t2": { visual: () => <DimensionWheel />, keyPoints:["Five dimensions: Processes, Extensions, Data, Integrations, Operations","Processes = sequences of actions in end-to-end flow","Integrations = mechanisms facilitating communication and data exchange between solutions"], jargon:[{term:"Processes",simple:"Sequences of actions arranged in an end-to-end flow.",inSystem:"SAP Signavio Process Navigator contains the standard SAP versions.",inExam:"Exact definition is directly testable: Sequences of actions, end-to-end flow.",color:"#0070F2"},{term:"Integrations",simple:"Mechanisms facilitating communication and data exchange between different solutions.",inSystem:"BTP Integration Suite keeps integrations clean.",inExam:"Exact definition is directly testable: Communication and data exchange.",color:"#059669"},{term:"Extensions",simple:"Custom functionality added to SAP beyond what is available out of the box.",inSystem:"Clean extensions are built on BTP, not inside S/4HANA core.",inExam:"Extensions ADD capability; Integrations CONNECT systems.",color:"#7C3AED"}], akshar:"Akshar 5 dimensions: Processes = custom procure-to-pay moving to SAP standard. Extensions = vendor rating app moving to BTP. Data = 320,000 material records. Integrations = custom IDocs to 3PL moving to BTP Integration Suite. Operations = reactive IT moving to proactive monitoring.", exam:"Two dimensions most frequently tested: Processes and Integrations. Know both exact definitions.", mistake:"Confusing Extensions with Integrations. Extensions add functionality. Integrations connect systems.", summary:["Five dimensions: Processes, Extensions, Data, Integrations, Operations — P-E-D-I-O.","Processes = end-to-end sequences. Integrations = communication between systems.","Extensions add functionality. Integrations connect systems. Do not mix them up."], questions: u1l3Questions.t2 },
    "u1l3-t3": { visual: () => <CleanStateVisual />, keyPoints:["Clean = best practices + right methodology + right tools applied throughout","A fresh S/4HANA Cloud with Signavio Process Navigator = clean from day one","Cleanliness must be actively maintained after go-live — not automatic"], jargon:[{term:"SAP Signavio Process Navigator",simple:"SAP library of standard, best-practice business process templates.",inSystem:"Companies compare current processes to SAP standard and adopt them where possible.",inExam:"Using Process Navigator = staying clean in the Processes dimension.",color:"#0070F2"},{term:"Cloud-Compliant Extensions",simple:"Custom developments built using BTP and standard SAP APIs.",inSystem:"These do not break when SAP upgrades the core because they sit outside it.",inExam:"Cloud-compliant extensions are part of the ideal Clean Core state.",color:"#059669"}], akshar:"Akshar S/4HANA on go-live day: clean — standard processes from Signavio Process Navigator, no custom code inside core. Two years later, a junior developer modifies a standard SAP table directly — the system immediately starts getting dirty.", exam:"Key testable line: A newly provisioned SAP S/4HANA Cloud system that uses standard processes from SAP Signavio Process Navigator is considered clean.", mistake:"Thinking a system stays clean automatically after go-live. Cleanliness must be actively maintained.", summary:["Clean = best practices + right methodology + right tools applied throughout.","Fresh S/4HANA Cloud + Signavio Process Navigator = clean from day one.","Ideal state: up-to-date software + cloud-compliant extensions + high-quality data + well-designed processes."], questions: u1l3Questions.t3 },
    "u1l3-t4": { visual: () => <CharacteristicsGrid />, keyPoints:["Five characteristics: Minimalism, Modularity, Scalability, Maintainability, Stability and Reliability","Exam trap options: Complexities and High dependency on customisations — what Clean Core AVOIDS","High performance and cost efficiency are outcomes, not official characteristics"], jargon:[{term:"Minimalism",simple:"Remove redundant or obsolete functionalities. Only keep what genuinely adds business value.",inSystem:"Deactivating old custom reports no one uses, removing replaced legacy integrations.",inExam:"Minimalism promotes simplicity by removing redundant or obsolete functionalities.",color:"#0070F2"},{term:"Modularity",simple:"ERP divided into independent, manageable pieces — update one without affecting others.",inSystem:"BTP extensions are modular — each app is independent of the S/4HANA core.",inExam:"Modularity facilitates dividing the ERP system into manageable modular components.",color:"#7C3AED"}], akshar:"Akshar old ECC: Not minimal 850 programs many unused. Not modular change one thing break three others. Not scalable new Pune plant took 8 months. Not maintainable only Rajesh knows the custom pricing code. Not reliable 2 critical incidents per month.", exam:"Multi-select: Minimalism + Scalability + Maintainability from that option set. Wrong options: Complexities + High dependency on customisations.", mistake:"Including High performance or Cost efficiency as characteristics. They are outcomes — not the 5 official characteristics.", summary:["Five: Minimalism, Modularity, Scalability, Maintainability, Stability and Reliability.","Exam trap: Complexities and High dependency on customisations are always wrong.","Tap each card above to see what each characteristic means."], questions: u1l3Questions.t4 },
    "u1l3-t5": { visual: () => <BTPStack />, keyPoints:["BTP = the place for ALL custom extensions in a Clean Core world","Two tracks: Low/No-code Build Apps and Process Automation and Pro-code BAS, ABAP Cloud, Build Code","SAP Discovery Center = official reference for all BTP capabilities"], jargon:[{term:"SAP Build Apps",simple:"SAP low-code/no-code tool for building mobile and web apps on BTP.",inSystem:"A business analyst can build apps for Akshar field team without writing code.",inExam:"SAP Build Apps = low/no-code on BTP. Part of the SAP Build suite.",color:"#059669"},{term:"Business Application Studio",simple:"SAP professional development environment IDE for building custom apps on BTP.",inSystem:"Where pro-code developers write ABAP Cloud or JavaScript-based extensions.",inExam:"Pro-code development on BTP = Business Application Studio or ABAP Cloud environment.",color:"#7C3AED"},{term:"Customer Centre of Expertise",simple:"An internal team that oversees SAP system governance, upgrades, and strategic decisions.",inSystem:"They ensure IT communicates with business units and makes upgrade decisions proactively.",inExam:"Recommended for ongoing operations — part of the Operations dimension.",color:"#0891B2"}], akshar:"Akshar needs a custom vendor rating system. Old approach: ABAP inside S/4HANA = dirty core. New approach: Priya developer builds it on BTP using Business Application Studio. Core untouched. Quarterly SAP update applied in one afternoon.", exam:"BTP = extension platform. SAP Discovery Center details BTP capabilities. Cloud ALM Operations apps = part of Enterprise Support at no additional cost.", mistake:"Thinking low-code tools on BTP are only for simple solutions. BTP low-code is enterprise-grade.", summary:["BTP = where ALL custom extensions go — keeping S/4HANA core untouched.","Low/No-code: Build Apps + Process Automation. Pro-code: BAS + ABAP Cloud + Build Code.","BTP capabilities go to SAP Discovery Center. Ongoing governance goes to Customer Centre of Expertise."], questions: u1l3Questions.t5 },
    "u1l3-t6": { visual: () => <div className="flex flex-col gap-3"><StatsRow stats={[{icon:"😰",to:70,suffix:"%",label:"IT budget on maintenance ECC dirty core",color:"#DC2626"},{icon:"✅",to:30,suffix:"%",label:"IT budget on maintenance Clean Core",color:"#059669"},{icon:"🔄",to:4,suffix:"x/yr",label:"SAP Cloud update frequency",color:"#0070F2"},{icon:"⏱️",to:18,suffix:" mo",label:"Typical ECC upgrade timeline",color:"#D97706"}]} /><BeforeAfter before={["Old software limits access to new features","Heavy customisation complicates upgrades","IT firefighting — no time for innovation","Security patches delayed","SAP seen as a liability"]} after={["Continuous innovation — new features quarterly","Standardised processes enable fast upgrades","IT focuses on new capabilities","SAP manages core security automatically","SAP positioned as a strategic asset"]} /></div>, keyPoints:["Old ERP: limited features, upgrade nightmares, IT firefighting, security lag","Clean Core ERP: continuous innovation, better data, efficient IT, improved security","Clean Core applies to both Public AND Private Edition customers"], jargon:[{term:"Continuous Innovation",simple:"The cloud model where SAP delivers new features quarterly — without major upgrade projects.",inSystem:"Only possible with a clean core. Dirty core cannot absorb quarterly updates.",inExam:"Clean Core enables continuous innovation adoption — a core benefit.",color:"#059669"}], akshar:"Akshar board: Current state = 70% IT budget on maintenance, 3 failed upgrades, no AI features, 2 critical incidents per month. Target state = 30% maintenance, 40% freed for innovation, quarterly updates in hours, Joule AI live from Day 1.", exam:"Flowchart contrasts: Old ERP old software limits access, customisation complicates upgrades vs Clean Core cloud software innovation, better data quality, efficient IT, security.", mistake:"Thinking Clean Core only applies to Public Cloud. S/4HANA Cloud Private Edition customers equally follow Clean Core.", summary:["Old ERP = limited features, upgrade nightmares, IT firefighting, security lag.","Clean Core = continuous innovation, better data, efficient IT, improved security.","Clean Core applies to both Public AND Private Edition — not just public cloud."], questions: u1l3Questions.t6 },
  };
}

function TopicSection({ topicId, topicNum, title, visual: v }: { topicId: string; topicNum: number; title: string; visual: TopicVisual }) {
  const [qOpen, setQOpen] = useState(false);
  return (
    <div id={topicId} className="mb-14">
      <div className="flex items-start gap-3 mb-5 pb-3.5 border-b-2 border-[#E2E8F0]">
        <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#0070F2] to-[#0057C2] flex items-center justify-center text-sm font-black text-white flex-shrink-0">{topicNum}</div>
        <h3 className="font-display text-[clamp(15px,2.5vw,19px)] font-black text-[#0F172A] leading-snug">{title}</h3>
      </div>
      <div className="mb-4">{v.visual()}</div>
      <div className="bg-white border border-[#E2E8F0] rounded-2xl p-4 mb-3.5">
        <p className="text-[10px] font-black text-[#94A3B8] uppercase tracking-[0.7px] mb-3">Key Points</p>
        {v.keyPoints.map((pt, i) => (<div key={i} className="flex items-start gap-2.5 mb-2 last:mb-0"><div className="w-[18px] h-[18px] rounded-md bg-[#EBF4FF] flex items-center justify-center text-[9px] font-black text-[#0070F2] flex-shrink-0 mt-0.5">→</div><p className="text-sm text-[#334155] leading-relaxed">{pt}</p></div>))}
      </div>
      <div className="mb-3.5">
        <p className="text-[10px] font-black text-[#6D28D9] uppercase tracking-[0.7px] mb-2.5">🟪 Jargon Buster — tap to flip</p>
        <div className="grid gap-2.5" style={{ gridTemplateColumns: `repeat(${Math.min(v.jargon.length, 3)}, 1fr)` }}>
          {v.jargon.map((j, i) => <FlipCard key={i} {...j} />)}
        </div>
      </div>
      <div className="bg-gradient-to-br from-[#FFFBEA] to-[#FEF9EE] border-2 border-[#FDE68A] rounded-2xl p-4 mb-3"><p className="text-[10px] font-black text-[#D97706] uppercase tracking-[0.7px] mb-2">🏭 Akshar Industries — Real Example</p><p className="text-[13.5px] text-[#78350F] leading-[1.75]">{v.akshar}</p></div>
      <div className="grid grid-cols-2 gap-2.5 mb-3.5">
        <div className="bg-gradient-to-br from-[#FFFBEA] to-[#FEF9EE] border-2 border-[#FDE68A] rounded-2xl p-4"><p className="text-[10px] font-black text-[#D97706] uppercase tracking-[0.6px] mb-2">🎯 Exam Insight</p><p className="text-xs text-[#78350F] leading-relaxed">{v.exam}</p></div>
        <div className="bg-gradient-to-br from-[#FEF2F2] to-[#FFF5F5] border-2 border-[#FECACA] rounded-2xl p-4"><p className="text-[10px] font-black text-[#DC2626] uppercase tracking-[0.6px] mb-2">⚠️ Common Mistake</p><p className="text-xs text-[#991B1B] leading-relaxed">{v.mistake}</p></div>
      </div>
      <div className="bg-gradient-to-br from-[#0070F2] to-[#0057C2] rounded-2xl p-5 mb-3.5">
        <p className="text-[10px] font-black text-white/60 uppercase tracking-[0.7px] mb-3">📦 30-Second Exam Summary</p>
        {v.summary.map((s, i) => (<div key={i} className="flex items-start gap-2.5 mb-2 last:mb-0"><div className="w-5 h-5 rounded-full bg-white/20 flex items-center justify-center text-[10px] font-black text-white flex-shrink-0 mt-0.5">{i+1}</div><p className="text-sm text-white/95 leading-relaxed font-medium">{s}</p></div>))}
      </div>
      <div className="border border-[#E2E8F0] rounded-2xl overflow-hidden">
        <button onClick={() => setQOpen(o => !o)} className="w-full px-4 py-3.5 flex items-center justify-between cursor-pointer transition-colors" style={{ background: qOpen ? "#EBF4FF" : "#F8FAFC" }}>
          <div className="flex items-center gap-2"><span>📝</span><span className="text-sm font-bold text-[#0F172A]">Practice Questions ({v.questions.length})</span></div>
          <span className="text-sm text-[#64748B] inline-block transition-transform" style={{ transform: qOpen ? "rotate(180deg)" : "none" }}>▾</span>
        </button>
        {qOpen && <div className="p-4 border-t border-[#E2E8F0]">{v.questions.map((q, i) => <PracticeQuestion key={i} question={q} qNum={i+1} />)}</div>}
      </div>
    </div>
  );
}

function LessonView({ lessonId }: { lessonId: string }) {
  const meta = LESSON_META[lessonId];
  const visuals = useMemo(() => getVisuals(), []);
  if (!meta) return (
    <div className="bg-gradient-to-br from-[#EBF4FF] to-[#F0F7FF] border border-[#BFDBFE] rounded-[20px] p-12 text-center">
      <div className="text-5xl mb-5">📖</div>
      <h3 className="font-display text-xl font-black text-[#1E3A5F] mb-3">Full Content — Coming Soon</h3>
      <p className="text-sm text-[#3B5E8C] leading-relaxed max-w-md mx-auto">This lesson is being built with visual diagrams, interactive elements, and Akshar Industries examples.</p>
    </div>
  );
  return (
    <div>
      <div className="bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl p-3 mb-5 flex items-start gap-2.5"><span className="text-sm flex-shrink-0 mt-0.5">ℹ️</span><p className="text-[11px] text-[#64748B] leading-relaxed"><strong className="text-[#334155]">Independently created content.</strong>{" "}Written from the author&apos;s professional SAP experience — not reproduced from any official SAP training material. All examples are fictional.</p></div>
      <div className="bg-gradient-to-br from-[#EBF4FF] to-[#F0F7FF] border border-[#BFDBFE] rounded-2xl p-4 mb-7"><p className="text-sm text-[#1E3A5F] leading-[1.75]">💡 {meta.intro}</p></div>
      <div className="bg-white border border-[#E2E8F0] rounded-2xl p-4 mb-9">
        <p className="text-[10px] font-black text-[#94A3B8] uppercase tracking-[0.7px] mb-2.5">Topics in this lesson</p>
        {meta.topicTitles.map((t, i) => (<a key={i} href={`#${meta.topics[i]}`} className="flex items-center gap-2.5 px-2 py-1.5 rounded-lg hover:bg-[#F8FAFC] transition-colors"><span className="w-5 h-5 rounded-md bg-[#EBF4FF] flex items-center justify-center text-[10px] font-black text-[#0070F2] flex-shrink-0">{i+1}</span><span className="text-sm text-[#334155] font-medium">{t}</span></a>))}
      </div>
      {meta.topics.map((tid, i) => { const visual = visuals[tid]; if (!visual) return null; return <TopicSection key={tid} topicId={tid} topicNum={i+1} title={meta.topicTitles[i]} visual={visual} />; })}
    </div>
  );
}

function Sidebar({ course, allLessons, activeId, onSelect, onSupport }: { course: typeof COURSE_REGISTRY[string]; allLessons: LessonWithUnit[]; activeId: string; onSelect: (id: string) => void; onSupport: () => void }) {
  const [done, setDone] = useState<Record<string, boolean>>({});
  const [search, setSearch] = useState("");
  useEffect(() => { setDone(getCourseProgress(course.id)); }, [course.id]);
  const total = allLessons.length, doneN = Object.values(done).filter(Boolean).length, prog = total > 0 ? Math.round((doneN/total)*100) : 0;
  const toggle = (id: string) => { const next = !done[id]; setDone(p => ({ ...p, [id]: next })); setLessonDone(course.id, id, next); };
  const filteredUnits = search.trim() ? course.units.map(u => ({ ...u, lessons: u.lessons.filter(l => l.title.toLowerCase().includes(search.toLowerCase())) })).filter(u => u.lessons.length > 0) : course.units;
  return (
    <aside className="flex flex-col bg-white border-r border-[#E2E8F0] h-full overflow-hidden">
      <div className="p-4 border-b border-[#E2E8F0] flex-shrink-0">
        <div className="flex justify-between items-center mb-2"><span className="text-[11px] font-bold text-[#475569] uppercase tracking-[0.5px]">Progress</span><span className="text-sm font-black text-[#0070F2]">{prog}%</span></div>
        <div className="h-1.5 bg-[#E2E8F0] rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-[#0070F2] to-[#38BDF8] rounded-full transition-all duration-500" style={{ width: `${prog}%` }} /></div>
        <p className="text-[11px] text-[#94A3B8] mt-1.5">{doneN} of {total} lessons done</p>
      </div>
      <div className="px-3.5 py-3 border-b border-[#E2E8F0] flex-shrink-0"><div className="relative"><span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-sm text-[#94A3B8]">🔍</span><input type="text" placeholder="Search lessons…" value={search} onChange={e => setSearch(e.target.value)} className="w-full pl-8 pr-3 py-2 bg-[#F8FAFC] border border-[#E2E8F0] rounded-lg text-xs text-[#334155] outline-none focus:border-[#0070F2] transition-colors" /></div></div>
      <div className="flex-1 overflow-y-auto py-2.5">
        {filteredUnits.map(unit => (<div key={unit.id} className="mb-1"><div className="px-4 py-2 flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: unit.color }} /><span className="text-[10px] font-black text-[#94A3B8] uppercase tracking-[0.7px]">{unit.title}</span></div>{unit.lessons.map(lesson => { const isA = activeId === lesson.id, isDone = !!done[lesson.id]; return (<button key={lesson.id} onClick={() => onSelect(lesson.id)} className="w-full text-left px-3.5 py-2.5 flex items-start gap-2.5 border-none transition-all border-l-[3px]" style={{ background: isA ? "#EBF4FF" : "transparent", borderLeftColor: isA ? "#0070F2" : "transparent", borderLeftStyle: "solid" }}><button onClick={e => { e.stopPropagation(); toggle(lesson.id); }} className="w-[17px] h-[17px] rounded flex-shrink-0 flex items-center justify-center transition-all mt-0.5 p-0" style={{ background: isDone ? "#0070F2" : "transparent", border: isDone ? "none" : "1.5px solid #CBD5E1" }}>{isDone && <span className="text-white text-[9px] font-black">✓</span>}</button><div className="flex-1 min-w-0"><p className="text-xs leading-snug break-words" style={{ fontWeight: isA ? 700 : 500, color: isA ? "#0057C2" : "#334155" }}>{lesson.title}</p><div className="flex items-center gap-1.5 mt-0.5"><span className="text-[10px] text-[#94A3B8]">~{lesson.time} min</span>{lesson.hasContent && <span className="text-[9px] bg-[#EDFAF1] text-[#065F46] px-1.5 py-px rounded font-bold">LIVE</span>}</div></div></button>); })}</div>))}
      </div>
      <div className="p-3.5 border-t border-[#E2E8F0] bg-[#FFF8F0] flex-shrink-0"><button onClick={onSupport} className="w-full bg-transparent border border-[#FDE68A] rounded-xl py-2.5 text-xs font-bold text-[#92400E] flex items-center justify-center gap-2 hover:bg-[#FEF3C7] transition-colors">☕ Support the Creator</button></div>
    </aside>
  );
}

export default function CoursePage({ params: paramsPromise }: { params: Promise<{ courseId: string }> }) {
  const { courseId } = use(paramsPromise);
  const course = COURSE_REGISTRY[courseId];
  const [activeId, setActiveId] = useState("");
  const [sideOpen, setSideOpen] = useState(true);
  const [modal, setModal] = useState(false);
  const mainRef = useRef<HTMLDivElement>(null);
  const allLessons: LessonWithUnit[] = useMemo(() => { if (!course) return []; return course.units.flatMap(u => u.lessons.map(l => ({ ...l, unitId: u.id, unitTitle: u.title, unitColor: u.color }))); }, [course]);
  useEffect(() => { if (allLessons.length > 0 && !activeId) setActiveId(allLessons[0].id); }, [allLessons, activeId]);
  useEffect(() => { if (mainRef.current) mainRef.current.scrollTop = 0; }, [activeId]);
  useEffect(() => { const h = (e: KeyboardEvent) => { if ((e.target as HTMLElement).tagName === "INPUT") return; const i = allLessons.findIndex(l => l.id === activeId); if (e.key === "ArrowRight" && i < allLessons.length-1) setActiveId(allLessons[i+1].id); if (e.key === "ArrowLeft" && i > 0) setActiveId(allLessons[i-1].id); }; window.addEventListener("keydown", h); return () => window.removeEventListener("keydown", h); }, [activeId, allLessons]);
  if (!course) return (<div className="min-h-screen flex flex-col items-center justify-center gap-4"><p className="text-xl font-black text-[#334155]">Course not found</p><Link href="/" className="text-[#0070F2] font-semibold hover:underline">← Back to Home</Link></div>);
  const ai = allLessons.findIndex(l => l.id === activeId), al = allLessons[ai], prev = ai > 0 ? allLessons[ai-1] : null, next = ai < allLessons.length-1 ? allLessons[ai+1] : null;
  const trunc = (s: string, n: number) => s.length > n ? s.slice(0,n)+"…" : s;
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-[#0B1829] border-b border-white/[0.07] sticky top-0 z-50">
        <div className="px-5 h-[58px] flex items-center justify-between gap-3">
          <div className="flex items-center gap-3 min-w-0">
            <Link href="/" className="flex-shrink-0 text-[#E2E8F0] border border-white/15 bg-white/[0.08] hover:bg-white/[0.16] text-xs font-medium px-3 py-1.5 rounded-lg transition-colors">← Back</Link>
            <div className="flex items-center gap-2.5 min-w-0">
              <div className="w-[34px] h-[34px] flex-shrink-0 bg-gradient-to-br from-[#0070F2] to-[#0057C2] rounded-[9px] flex items-center justify-center text-[17px]">📘</div>
              <div className="min-w-0"><p className="text-[15px] font-bold text-[#F1F5F9] font-display tracking-tight leading-none">SAPedia</p><p className="text-[10px] text-[#475569] mt-0.5 truncate">{course.title}</p></div>
            </div>
          </div>
          <button onClick={() => setModal(true)} className="flex-shrink-0 flex items-center gap-1.5 bg-white/[0.08] hover:bg-white/[0.16] border border-white/15 text-[#E2E8F0] text-xs font-medium px-3 py-1.5 rounded-lg transition-colors"><span>☕</span><span className="hidden sm:inline">Support Creator</span></button>
        </div>
      </header>
      <div className="flex flex-1 overflow-hidden" style={{ height: "calc(100vh - 58px)" }}>
        <div className="flex-shrink-0 transition-all duration-300 overflow-hidden" style={{ width: sideOpen ? 272 : 0, minWidth: sideOpen ? 272 : 0 }}>
          <div className="w-[272px] h-full"><Sidebar course={course} allLessons={allLessons} activeId={activeId} onSelect={setActiveId} onSupport={() => setModal(true)} /></div>
        </div>
        <div className="flex flex-col flex-1 overflow-hidden">
          <div className="h-[50px] px-5 flex-shrink-0 bg-white border-b border-[#E2E8F0] flex items-center gap-3">
            <button onClick={() => setSideOpen(o => !o)} className="flex-shrink-0 bg-transparent hover:bg-[#F8FAFC] border border-[#E2E8F0] rounded-lg px-2.5 py-1.5 text-sm text-[#64748B] transition-colors">{sideOpen ? "◀" : "▶"}</button>
            {al && (<div className="flex-1 flex items-center gap-2 min-w-0 overflow-hidden"><div className="w-2 h-2 rounded-full flex-shrink-0" style={{ background: al.unitColor }} /><span className="text-xs font-semibold text-[#334155] flex-shrink-0 hidden sm:block">{al.unitTitle}</span><span className="text-[#CBD5E1] hidden sm:block">›</span><span className="text-xs text-[#0F172A] font-medium truncate">{al.title}</span></div>)}
            <span className="text-xs text-[#94A3B8] flex-shrink-0">{ai+1}/{allLessons.length}</span>
          </div>
          <div ref={mainRef} className="flex-1 overflow-y-auto">
            <div className="max-w-[820px] mx-auto px-[clamp(20px,4vw,36px)] py-[clamp(28px,5vw,48px)]">
              {al && (<div><div className="mb-7"><div className="flex flex-wrap items-center gap-2.5 mb-3"><span className="text-[11px] font-bold px-2.5 py-1 rounded-full uppercase tracking-[0.4px]" style={{ background: `${al.unitColor}18`, color: al.unitColor }}>{al.unitTitle}</span><span className="text-xs text-[#94A3B8]">⏱ ~{al.time} min</span>{al.hasContent && <span className="text-[11px] bg-[#EDFAF1] text-[#065F46] px-2 py-0.5 rounded-md font-bold">✅ Visual Content</span>}</div><h1 className="font-display text-[clamp(20px,3.5vw,30px)] font-black text-[#0F172A] leading-snug">{al.title}</h1><div className="w-12 h-[3px] rounded-full mt-2.5" style={{ background: `linear-gradient(90deg,${al.unitColor},${al.unitColor}60)` }} /></div><LessonView lessonId={al.id} /></div>)}
            </div>
          </div>
          <div className="px-5 py-3.5 flex-shrink-0 bg-white border-t border-[#E2E8F0] flex justify-between items-center gap-3">
            <button onClick={() => prev && setActiveId(prev.id)} disabled={!prev} className="px-4 py-2.5 rounded-xl text-sm font-semibold transition-all border" style={{ background: prev?"#fff":"#F8FAFC", borderColor: prev?"#E2E8F0":"transparent", color: prev?"#334155":"#CBD5E1", cursor: prev?"pointer":"default" }}>← {prev?trunc(prev.title,22):"Previous"}</button>
            <span className="text-xs text-[#94A3B8] flex-shrink-0">{ai+1} / {allLessons.length}</span>
            <button onClick={() => next && setActiveId(next.id)} disabled={!next} className="px-4 py-2.5 rounded-xl text-sm font-semibold border-0" style={{ background: next?"#0070F2":"#F8FAFC", color: next?"#fff":"#CBD5E1", cursor: next?"pointer":"default" }}>{next?trunc(next.title,22):"Next"} →</button>
          </div>
        </div>
      </div>
      {modal && <DonationModal onClose={() => setModal(false)} trigger="sidebar" />}
    </div>
  );
}
